// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBankingApplication.DAL;

#nullable disable

namespace OnlineBankingApplication.Migrations.OnlineBankingDb
{
    [DbContext(typeof(OnlineBankingDbContext))]
    partial class OnlineBankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineBankingApplication.Models.Admin", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MinimumBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProductId")
                        .HasName("PK__Admin__B40CC6CDB9B98064");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<DateTime?>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F2398305CFE6C");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.BankAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Ifsccode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("IFSCCode");

                    b.Property<DateTime?>("OpenedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("AccountId")
                        .HasName("PK__BankAcco__349DA5A61B68F450");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "AccountNumber" }, "UQ__BankAcco__BE2ACD6FC06F0C7C")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Ifsccode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("IFSCCode");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BeneficiaryId")
                        .HasName("PK__Benefici__3FBA95F51CEB5313");

                    b.HasIndex("CustomerId");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.BillPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Paid");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("PaymentId")
                        .HasName("PK__BillPaym__9B556A38FDDEB908");

                    b.HasIndex("AccountId");

                    b.HasIndex("BillId");

                    b.HasIndex("TransactionId");

                    b.ToTable("BillPayments");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.ChequeBookRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfLeaves")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("RequestId")
                        .HasName("PK__ChequeBo__33A8517A52043CD3");

                    b.HasIndex("AccountId");

                    b.ToTable("ChequeBookRequests");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AadhaarNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pannumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PANNumber");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64D8F7731090");

                    b.HasIndex(new[] { "Pannumber" }, "UQ__Customer__04D051B40A2AECB4")
                        .IsUnique()
                        .HasFilter("[PANNumber] IS NOT NULL");

                    b.HasIndex(new[] { "AadhaarNumber" }, "UQ__Customer__72CF795925F47F05")
                        .IsUnique()
                        .HasFilter("[AadhaarNumber] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.ProfileUpdateRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("NewAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("RequestId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ProfileUpdateRequest", (string)null);
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ReceiverAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Success");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__55433A6B72374B02");

                    b.HasIndex("ReceiverAccountId");

                    b.HasIndex("SenderAccountId");

                    b.HasIndex(new[] { "TransactionReference" }, "UQ__Transact__6783D2A1814146F2")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.UtilityBill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BillId")
                        .HasName("PK__UtilityB__11F2FC6A312DC860");

                    b.ToTable("UtilityBills");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.BankAccount", b =>
                {
                    b.HasOne("OnlineBankingApplication.Models.Customer", "Customer")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_BankAccounts_Customers");

                    b.HasOne("OnlineBankingApplication.Models.Admin", "Product")
                        .WithMany("BankAccounts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_BankAccounts_Product");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Beneficiary", b =>
                {
                    b.HasOne("OnlineBankingApplication.Models.Customer", "Customer")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Beneficiary_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.BillPayment", b =>
                {
                    b.HasOne("OnlineBankingApplication.Models.BankAccount", "Account")
                        .WithMany("BillPayments")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_BillPayments_Account");

                    b.HasOne("OnlineBankingApplication.Models.UtilityBill", "Bill")
                        .WithMany("BillPayments")
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("FK_BillPayments_Bill");

                    b.HasOne("OnlineBankingApplication.Models.Transaction", "Transaction")
                        .WithMany("BillPayments")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK_BillPayments_Transaction");

                    b.Navigation("Account");

                    b.Navigation("Bill");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.ChequeBookRequest", b =>
                {
                    b.HasOne("OnlineBankingApplication.Models.BankAccount", "Account")
                        .WithMany("ChequeBookRequests")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_ChequeRequest_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.ProfileUpdateRequest", b =>
                {
                    b.HasOne("OnlineBankingApplication.Models.Customer", "Customer")
                        .WithMany("ProfileUpdateRequests")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfileUpdateRequest_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Transaction", b =>
                {
                    b.HasOne("OnlineBankingApplication.Models.BankAccount", "ReceiverAccount")
                        .WithMany("TransactionReceiverAccounts")
                        .HasForeignKey("ReceiverAccountId")
                        .HasConstraintName("FK_Transaction_Receiver");

                    b.HasOne("OnlineBankingApplication.Models.BankAccount", "SenderAccount")
                        .WithMany("TransactionSenderAccounts")
                        .HasForeignKey("SenderAccountId")
                        .HasConstraintName("FK_Transaction_Sender");

                    b.Navigation("ReceiverAccount");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Admin", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.BankAccount", b =>
                {
                    b.Navigation("BillPayments");

                    b.Navigation("ChequeBookRequests");

                    b.Navigation("TransactionReceiverAccounts");

                    b.Navigation("TransactionSenderAccounts");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Customer", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Beneficiaries");

                    b.Navigation("ProfileUpdateRequests");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.Transaction", b =>
                {
                    b.Navigation("BillPayments");
                });

            modelBuilder.Entity("OnlineBankingApplication.Models.UtilityBill", b =>
                {
                    b.Navigation("BillPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
